### ISSUE TITLE
matmul: Input operand 0 does not have enough dimensions - step#5

### ISSUE THREAD

**Issue by miaoqiz** [cvg/SOLD2#24]
Hi there,

At step#5, after changing the "return_type" in "wireframe_dataset.yaml", there is an error as below:

---------------------------------------------------------------------------------------------------------------------------------------

  File "SOLD2/dataset/wireframe_dataset.py", line 453, in get_line_points
    warped_points = warp_points(line_points, H1)
  File "SOLD2/misc/geometry_utils.py", line 13, in warp_points
    new_points = (homography @ new_points.T).T
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

---------------------------------------------------------------------------------------------------------------------------------------

Thanks for the advice!

**Comment by rpautrat** [comment]
Hi,

Did you use 'paired' or 'paired_desc' for the return_type? It should be 'paired_desc' if you want to train with the descriptor. The 'paired' parameter is actually deprecated and should be removed I think.

If you did use 'paired_desc', could please display the full error message?

**Comment by miaoqiz** [comment]
Hi,

Thanks for the reply!

I did use "paired_desc". Here is the full error message:

------------------------------------------------------------------------------------------

================== Training ====================
Traceback (most recent call last):
  File "experiment.py", line 227, in <module>
    export_dataset_mode=args.export_dataset_mode, device=device)
  File "experiment.py", line 110, in main
    train(args, dataset_cfg, model_cfg, output_path)
  File "experiment.py", line 82, in train
    train_net(args, dataset_cfg, model_cfg, output_path)
  File "SOLD2/train.py", line 179, in train_net
    epoch=epoch)
  File "SOLD2/train.py", line 227, in train_single_epoch
    for idx, data in enumerate(train_loader):
  File ".local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File ".local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File ".local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File ".local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "SOLD2/dataset/wireframe_dataset.py", line 974, in __getitem__
    data, scale=scale)
  File "SOLD2/dataset/wireframe_dataset.py", line 745, in preprocessing_exported_paired_desc
    scale=scale, h_crop=h_crop, w_crop=w_crop)
  File "SOLD2/dataset/wireframe_dataset.py", line 669, in train_preprocessing_exported
    img_size=image_size, warp=warp)
  File "SOLD2/dataset/wireframe_dataset.py", line 453, in get_line_points
    warped_points = warp_points(line_points, H1)
  File "SOLD2/misc/geometry_utils.py", line 13, in warp_points
    new_points = (homography @ new_points.T).T
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

------------------------------------------------------------------------------------------

Thanks!

**Comment by miaoqiz** [comment]
Any updates on the fix? :)

Thanks a lot!

**Comment by rpautrat** [comment]
Hi,

Sorry for the late reply. Did you do any change to the original code? In particular, are the homographic augmentations enabled in your config file?  I ran it on my side with a fresh git clone and everything worked smoothly.

The code should theoretically not go to this location, "File "SOLD2/dataset/wireframe_dataset.py", line 453, in get_line_points". So something is messed up in your code, somehow. I recommend printing the variables 'warp', 'H1' and 'H2' and understand what each one is doing. In your case, the error is generated by H1 being None, whereas this shouldn't happen. So try to understand why it becomes a None in your case.

**Comment by miaoqiz** [comment]
Hi @rpautrat ,

Thanks for reminding me of enabling augmentations in the config file. 

It is in the training now.

Thanks so much and have a good week!
