### ISSUE TITLE
Which path is the pre-trained model placed in?

### ISSUE THREAD

**Issue by nmanhong** [cvg/SOLD2#81]
hello：
Which path is the pre-trained model placed in?  Is there a more detailed tutorial for this training for novices?

**Comment by rpautrat** [comment]
Hi, the paths to the pre-trained models are in the Readme, under "Pretrained models".
There are already detailed steps to reproduce the training in this Readme. It would be hard to make this more detailed... To fully understand exactly which step is doing what, reading the original paper might be helpful though.

**Comment by nmanhong** [comment]
Sorry, I didn't ask where is the link for the pretrained model? I want to know which folder should I put the pre-trained model I downloaded? I have downloaded the pre-trained model
Could you provide me the py file that I want to train my own data, I have checked your #19, but my level is very low, this may be difficult for me

**Comment by rpautrat** [comment]
Sorry, I misread your question. You can place the pre-trained model wherever you want, as long as you give the right path later when calling the model. When initializing `LineMatcher`, the second argument should be the path to the pre-trained model. For example, in the notebook https://github.com/cvg/SOLD2/blob/main/notebooks/match_lines.ipynb, the pre-trained model should be placed in a folder `pretrained_models` at the root of the project.

There is no python file to train on a custom dataset, you have to create it yourself by copying the structure of existing ones (e.g. [holicity_dataset.py](https://github.com/cvg/SOLD2/blob/main/sold2/dataset/holicity_dataset.py)), and following the instructions of the issue you already mentioned. This requires unfortunately a minimal understanding of the code and some work for you, but I can't write it for you.

**Comment by nmanhong** [comment]
@rpautrat  Hi, can you provide me a final model that you have trained? I want to test the effect on my data set, and then consider whether I need to retrain

**Comment by rpautrat** [comment]
Hi, our final model is the one available on the Readme, [sold2_wireframe.tar](https://www.polybox.ethz.ch/index.php/s/blOrW89gqSLoHOk/download), there is no other one. We did retrain one on holicity, but observed a similar performance, so it is not public.

**Comment by nmanhong** [comment]
@rpautrat 
Hi, hello, I downloaded this file and saw the usage in README like this
' python -m sold2.export_line_features --img_list /home/loongson/nmh/code/img/1.tif --output_folder /home/loongson/nmh/code/test --checkpoint_path ./sold2_wireframe.tar '
an error message
' Traceback (most recent call last):
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/loongson/nmh/code/SOLD2/sold2/export_line_features.py", line 68, in <module>
    config = load_config(args.config)
  File "/home/loongson/nmh/code/SOLD2/sold2/experiment.py", line 25, in load_config
    raise ValueError("[Error] The provided config path is not valid.")
ValueError: [Error] The provided config path is not valid. '

**Comment by nmanhong** [comment]
Is it necessary to train or modify other methods?

**Comment by nmanhong** [comment]
python -m sold2.export_line_features --img_list /home/loongson/nmh/code/img/1.tif --output_folder /home/loongson/nmh/code/test/2.tif --checkpoint_path ./sold2_wireframe.tar --config sold2/config/export_line_features.yaml --multiscale


	--------Initializing model----------
	 [Debug] Adding w_junc with value 0.000000 to model
	 [Debug] Adding w_heatmap with value 0.000000 to model
	 [Debug] Adding w_desc with value 0.000000 to model
	Model architecture: simple
	Backbone: lcnn
	Junction decoder: superpoint_decoder
	Heatmap decoder: pixel_shuffle
	-------------------------------------
[Debug] detect_thresh: 0.5
[Debug] num_samples: 64
[Debug] sampling_method: local_max
[Debug] inlier_thresh: 0.99
[Debug] use_candidate_suppression: True
[Debug] nms_dist_tolerance: 3.0
[Debug] use_heatmap_refinement: True
[Debug] heatmap_refine_cfg: {'mode': 'local', 'ratio': 0.2, 'valid_thresh': 0.001, 'num_blocks': 20, 'overlap_ratio': 0.5}
[Debug] use_junction_refinement: True
[Debug] junction_refine_cfg: {'num_perturbs': 9, 'perturb_interval': 0.25}
	 Successfully initialized model
  0%|                                                                                                   | 0/38438 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/loongson/nmh/code/SOLD2/sold2/export_line_features.py", line 74, in <module>
    args.output_folder, args.multiscale)
  File "/home/loongson/nmh/code/SOLD2/sold2/export_line_features.py", line 31, in export_descriptors
    img = torch.tensor(img[None, None] / 255., dtype=torch.float,
TypeError: 'NoneType' object is not subscriptable

**Comment by nmanhong** [comment]
python -m sold2.export_line_features --img_list ./img.txt --output_folder /home/loongson/nmh/code/test/2.tif --checkpoint_path ./sold2_wireframe.tar --config sold2/config/export_line_features.yaml


	--------Initializing model----------
	 [Debug] Adding w_junc with value 0.000000 to model
	 [Debug] Adding w_heatmap with value 0.000000 to model
	 [Debug] Adding w_desc with value 0.000000 to model
	Model architecture: simple
	Backbone: lcnn
	Junction decoder: superpoint_decoder
	Heatmap decoder: pixel_shuffle
	-------------------------------------
[Debug] detect_thresh: 0.5
[Debug] num_samples: 64
[Debug] sampling_method: local_max
[Debug] inlier_thresh: 0.99
[Debug] use_candidate_suppression: True
[Debug] nms_dist_tolerance: 3.0
[Debug] use_heatmap_refinement: True
[Debug] heatmap_refine_cfg: {'mode': 'local', 'ratio': 0.2, 'valid_thresh': 0.001, 'num_blocks': 20, 'overlap_ratio': 0.5}
[Debug] use_junction_refinement: True
[Debug] junction_refine_cfg: {'num_perturbs': 9, 'perturb_interval': 0.25}
	 Successfully initialized model
  0%|                                                                                                       | 0/2 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/loongson/nmh/code/SOLD2/sold2/export_line_features.py", line 74, in <module>
    args.output_folder, args.multiscale)
  File "/home/loongson/nmh/code/SOLD2/sold2/export_line_features.py", line 35, in export_descriptors
    ref_detection = line_matcher.line_detection(img)
  File "/home/loongson/nmh/code/SOLD2/sold2/model/line_matcher.py", line 73, in line_detection
    net_outputs = self.model(input_image)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/loongson/nmh/code/SOLD2/sold2/model/model_util.py", line 82, in forward
    features = self.backbone_net(input_images)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/loongson/nmh/code/SOLD2/sold2/model/nets/backbone.py", line 23, in forward
    return self.net(input_images)[1]
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/loongson/nmh/code/SOLD2/sold2/model/nets/lcnn_hourglass.py", line 188, in forward
    x = self.conv1(x)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/home/loongson/venv/anaconda3/envs/tes/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by nmanhong** [comment]
When I changed it to cpu, it can be tested, but the test result is only a .npz file, how can I see the test effect picture of this file?
