### ISSUE TITLE
KeyError: "Unable to open object (object 'draw_stripes_multiseg\\019084' doesn't exist)"

### ISSUE THREAD

**Issue by xhcswjtu** [cvg/SOLD2#91]
Hi,during  Step 1,I got error after successfully initializing model:
Traceback (most recent call last):
  File "D:\anaconda3\envs\DeepL\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\DeepL\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\line detection\SOLD2-main\sold2\experiment.py", line 228, in <module>
    main(args, dataset_cfg, model_cfg,
  File "D:\line detection\SOLD2-main\sold2\experiment.py", line 112, in main
    train(args, dataset_cfg, model_cfg, output_path)
  File "D:\line detection\SOLD2-main\sold2\experiment.py", line 84, in train
    train_net(args, dataset_cfg, model_cfg, output_path)
  File "D:\line detection\SOLD2-main\sold2\train.py", line 171, in train_net
    train_single_epoch(
  File "D:\line detection\SOLD2-main\sold2\train.py", line 227, in train_single_epoch
    for idx, data in enumerate(train_loader):
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\_utils.py", line 722, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\DeepL\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\line detection\SOLD2-main\sold2\dataset\synthetic_dataset.py", line 649, in __getitem__
    data = self.get_data_from_datapoint(datapoint, reader)
  File "D:\line detection\SOLD2-main\sold2\dataset\synthetic_dataset.py", line 408, in get_data_from_datapoint
    data = reader[datapoint]
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\anaconda3\envs\DeepL\lib\site-packages\h5py\_hl\group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5o.pyx", line 241, in h5py.h5o.open
KeyError: "Unable to open object (object 'draw_stripes_multiseg\\019084' doesn't exist)"
Sorry to bother you , can you give me some suggestions,thank you！

**Comment by LHZXY0** [comment]
so do i,I'm going to crash！

**Comment by LHZXY0** [comment]
文件的格式应该为draw_stripes_multiseg/019084
